export const LOAD_POKEMON = 'LOAD_POKEMON';
export const LOAD_POKEMON_SUCCESS = 'LOAD_POKEMON_SUCCESS';
export const LOAD_POKEMON_FAILED = 'LOAD_POKEMON_FAILED';

export const LOAD_POKEMON_DETAIL = 'LOAD_POKEMON_DETAIL';
export const LOAD_POKEMON_DETAIL_SUCCESS = 'LOAD_POKEMON_DETAIL_SUCCESS';
export const LOAD_POKEMON_DETAIL_FAILED = 'LOAD_POKEMON_DETAIL_FAILED';

export const LOAD_POKEMON_BY_TYPE = 'LOAD_POKEMON_BY_TYPE';
export const LOAD_POKEMON_BY_TYPE_SUCCESS = 'LOAD_POKEMON_BY_TYPE_SUCCESS';
export const LOAD_POKEMON_BY_TYPE_FAILED = 'LOAD_POKEMON_BY_TYPE_FAILED';

export const LOAD_POKEMON_TYPE = 'LOAD_POKEMON_TYPE';
export const LOAD_POKEMON_TYPE_SUCCESS = 'LOAD_POKEMON_TYPE_SUCCESS';

export const SET_FILTER = 'SET_FILTER';
